version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fastify-poc
    volumes:
      - mongo-data:/data/db

  fastify-poc:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - mongodb
    volumes:
      - .:/app
        - /app/node_modules

volumes:
  mongo-data:
    driver: local
