version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: fastify-poc-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fastify-poc
    volumes:
      - mongo-data:/data/db
    networks:
      - fastify-poc-net

  fastify-poc:
    container_name: fastify-poc-app
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      kafka:
        condition: service_healthy
      mongodb:
        condition: service_started
    networks:
      - fastify-poc-net

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: fastify-poc-zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - fastify-poc-net

  kafka:
    image: bitnami/kafka:3.5.1
    container_name: fastify-poc-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9093", "--list"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - fastify-poc-net

  redpanda-console:
    image: docker.io/redpandadata/console:latest
    container_name: fastify-poc-kafka-console
    ports:
      - "8081:8080"
    environment:
      - KAFKA_BROKERS=kafka:9093
    depends_on:
      - kafka
    networks:
      - fastify-poc-net

  prometheus:
    image: prom/prometheus:latest
    container_name: fastify-poc-prometheus
    ports:
      - "9090:9090"
    depends_on:
      - fastify-poc
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - fastify-poc-net

volumes:
  mongo-data:
    driver: local

networks:
  fastify-poc-net:
    driver: bridge