apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: "0.0.0.0:4318"

    exporters:
      zipkin:
        endpoint: "http://zipkin:9411/api/v2/spans"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [zipkin]

