apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda-console
  template:
    metadata:
      labels:
        app: redpanda-console
    spec:
      containers:
        - name: console
          image: docker.io/redpandadata/console:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKERS
              value: kafka:9092